version: '3.8'

services:
  backend:
    image: ${ECR_REGISTRY}/leum-server:latest
    ports:
      - "8080:8080" # tomcat 포트 오픈
      - "8081:8081" # 헬스체크용 포트 오픈
    restart: always # 예기치 않은 종료가 발생할 경우 항상 재시작을 시도함
    env_file: # 필요한 환경변수 주입
      - .env
    volumes:
      - ./application.yml:/leum-server/config/application.yml
    networks:
      - leum-server

networks: # 지금 당장 필요하지는 않지만 추후 확장을 고려하여 미리 추가
  leum-server:
    driver: bridge