version: '3.8'

services:
  backend:
    image: ${ECR_REGISTRY}/leum-server:latest
    build: # Dockerfile을 사용하여 이미지를 빌드하도록 설정
      context: . # Dockerfile 의 경로 명세
      dockerfile: Dockerfile # 명시적으로 Dockerfile 명을 지정
    ports:
      - "8080:8080" # tomcat 포트번호 오픈
    restart: always # 예기치 않은 종료가 발생할 경우 항상 재시작을 시도함
    env_file: # 필요한 환경변수 주입
      - .env
    volumes:
      - ./application.yml:/leum-server/config/application.yml
    networks:
      - leum-server

networks: # 지금 당장 필요하지는 않지만 추후 확장을 고려하여 미리 추가
  leum-server:
    driver: bridge